#!/bin/bash

(( $(cliphist list | wc -l) > 100 )) && {
  [ -f "$HOME/.cache/cliphist/db" ] && rm ~/.cache/cliphist/db
}

hyprctl dispatch focuswindow foot
hyprctl setcursor "GoogleDot-Black" 24 
gnome-settings(){
  gnomeschema="org.gnome.desktop.interface"
  theme="FlatColor"
  [ -d "$HOME/.themes/oomix-nik-theme" ] && theme="oomix-nik-theme"
  gsettings set "$gnomeschema" gtk-theme "$theme"
  gsettings set "$gnomeschema" icon-theme 'la-capitaine'
  gsettings set "$gnomeschema" cursor-theme 'GoogleDot-Black'
  gsettings set "$gnomeschema" font-name 'Comic Code Ligatures Nerd Font'
}

gnome-settings
#[ -f "$HOME"/binaries/utils/idle ] && "$HOME"/binaries/utils/idle
#[ -f "$HOME"/binaries/utils/wbar ] && "$HOME"/binaries/utils/wbar
#[ -f "$HOME"/binaries/hypr/ui ] && "$HOME"/binaries/hypr/ui
#notify-send "Reloaded Hyprland" -t 2000
