#!/bin/bash

(( $(cliphist list | wc -l) > 100 )) && {
  [ -f "$HOME/.cache/cliphist/db" ] && rm ~/.cache/cliphist/db
}

hyprctl dispatch focuswindow foot

# gnome-settings(){
#   gnomeschema="org.gnome.desktop.interface"

#   gsettings set "$gnomeschema" gtk-theme 'FlatColor'
#   gsettings set "$gnomeschema" icon-theme 'la-capitaine'
#   gsettings set "$gnomeschema" cursor-theme 'GoogleDot-Black'
#   gsettings set "$gnomeschema" font-name 'Comic Code Ligatures'
# }

# gnome-settings
#[ -f "$HOME"/binaries/utils/idle ] && "$HOME"/binaries/utils/idle
#[ -f "$HOME"/binaries/utils/wbar ] && "$HOME"/binaries/utils/wbar
#[ -f "$HOME"/binaries/hypr/ui ] && "$HOME"/binaries/hypr/ui
#notify-send "Reloaded Hyprland" -t 2000
