# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#f5dccf"          # Main text color
theme[title]="#f5dccf"            # Title color for boxes
theme[hi_fg]="#7898B2"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#ab9a90"       # Color of inactive/disabled text
theme[graph_text]="#A6A1B1"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#10121e"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#2b5675"       # Background color of selected item in processes box
theme[selected_fg]="#f5dccf"       # Foreground color of selected item in processes box
theme[proc_misc]="#A6A1B1"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#7898B2"           # Cpu box outline color
theme[mem_box]="#366C93"           # Memory/disks box outline color
theme[net_box]="#7898B2"           # Net up/down box outline color
theme[proc_box]="#366C93"          # Processes box outline color
theme[div_line]="#366C93"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#ab9a90"          # Background color of the percentage meters
theme[used_start]="#A6A1B1"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#A6A1B1"
theme[available_start]="#DFB1B5"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#DFB1B5"
theme[cached_start]="#A6A1B1"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#A6A1B1"
theme[free_start]="#DFB1B5"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#DFB1B5"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#7898B2"        # CPU graph colors
theme[cpu_mid]="#1A99AD"
theme[cpu_end]="#366C93"
theme[download_start]="#A6A1B1"    # Download graph colors
theme[download_mid]="#366C93"
theme[download_end]="#366C93"  
theme[upload_start]="#1A99AD"     # Upload graph colors
theme[upload_mid]="#1A99AD"
theme[upload_end]="#DFB1B5"
theme[process_start]="#A6A1B1"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#DFB1B5"
theme[process_end]="#8C9AB4"