# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#f3deea"          # Main text color
theme[title]="#f3deea"            # Title color for boxes
theme[hi_fg]="#4A57A9"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#aa9ba3"       # Color of inactive/disabled text
theme[graph_text]="#967CBD"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#0E101E"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#7a5861"       # Background color of selected item in processes box
theme[selected_fg]="#f3deea"       # Foreground color of selected item in processes box
theme[proc_misc]="#967CBD"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#4A57A9"           # Cpu box outline color
theme[mem_box]="#996E7A"           # Memory/disks box outline color
theme[net_box]="#4A57A9"           # Net up/down box outline color
theme[proc_box]="#996E7A"          # Processes box outline color
theme[div_line]="#996E7A"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#aa9ba3"          # Background color of the percentage meters
theme[used_start]="#967CBD"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#967CBD"
theme[available_start]="#C99CBB"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#C99CBB"
theme[cached_start]="#967CBD"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#967CBD"
theme[free_start]="#C99CBB"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#C99CBB"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#4A57A9"        # CPU graph colors
theme[cpu_mid]="#605E91"
theme[cpu_end]="#996E7A"
theme[download_start]="#967CBD"    # Download graph colors
theme[download_mid]="#996E7A"
theme[download_end]="#996E7A"  
theme[upload_start]="#605E91"     # Upload graph colors
theme[upload_mid]="#605E91"
theme[upload_end]="#C99CBB"
theme[process_start]="#967CBD"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#C99CBB"
theme[process_end]="#8E7592"