# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#adbdc5"          # Main text color
theme[title]="#adbdc5"            # Title color for boxes
theme[hi_fg]="#315868"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#798489"       # Color of inactive/disabled text
theme[graph_text]="#8E6762"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#010E12"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#11373f"       # Background color of selected item in processes box
theme[selected_fg]="#adbdc5"       # Foreground color of selected item in processes box
theme[proc_misc]="#8E6762"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#315868"           # Cpu box outline color
theme[mem_box]="#16454F"           # Memory/disks box outline color
theme[net_box]="#315868"           # Net up/down box outline color
theme[proc_box]="#16454F"          # Processes box outline color
theme[div_line]="#16454F"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#798489"          # Background color of the percentage meters
theme[used_start]="#8E6762"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#8E6762"
theme[available_start]="#58748C"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#58748C"
theme[cached_start]="#8E6762"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#8E6762"
theme[free_start]="#58748C"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#58748C"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#315868"        # CPU graph colors
theme[cpu_mid]="#2E4850"
theme[cpu_end]="#16454F"
theme[download_start]="#8E6762"    # Download graph colors
theme[download_mid]="#16454F"
theme[download_end]="#16454F"  
theme[upload_start]="#2E4850"     # Upload graph colors
theme[upload_mid]="#2E4850"
theme[upload_end]="#58748C"
theme[process_start]="#8E6762"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#58748C"
theme[process_end]="#555D62"